import libraries necessary

In [13]:
import pandas as pd

In [16]:
df = pd.read_csv("C:/Users/XRona/datasets/covid-world-vaccination-progress/country_vaccinations.csv")
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [17]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
73004,Zimbabwe,ZWE,2022-01-21,7496882.0,4234640.0,3262242.0,13650.0,10405.0,49.67,28.06,21.62,689.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
73005,Zimbabwe,ZWE,2022-01-22,7506786.0,4239537.0,3267249.0,9904.0,10567.0,49.74,28.09,21.65,700.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
73006,Zimbabwe,ZWE,2022-01-23,7512903.0,4242647.0,3270256.0,6117.0,10631.0,49.78,28.11,21.67,704.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
73007,Zimbabwe,ZWE,2022-01-24,7517985.0,4245063.0,3272922.0,5082.0,10273.0,49.81,28.13,21.69,681.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
73008,Zimbabwe,ZWE,2022-01-25,7525574.0,4248576.0,3276998.0,7589.0,9579.0,49.86,28.15,21.71,635.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73009 entries, 0 to 73008
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              73009 non-null  object
 1   iso_code                             73009 non-null  object
 2   date                                 73009 non-null  object
 3   total_vaccinations                   38209 non-null  float64
 4   people_vaccinated                    36254 non-null  float64
 5   people_fully_vaccinated              33488 non-null  float64
 6   daily_vaccinations_raw               31214 non-null  float64
 7   daily_vaccinations                   72646 non-null  float64
 8   total_vaccinations_per_hundred       38209 non-null  float64
 9   people_vaccinated_per_hundred        36254 non-null  float64
 10  people_fully_vaccinated_per_hundred  33488 non-null  float64
 11  daily_vaccinations_per_million       72646 non-null  float64
 12  vaccines                             73009 non-null  object
 13  source_name                          73009 non-null  object
 14  source_website                       73009 non-null  object
dtypes: float64(9), object(6)
memory usage: 8.4+ MB

In [19]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,3.820900e+04,3.625400e+04,3.348800e+04,3.121400e+04,7.264600e+04,38209.000000,36254.000000,33488.000000,72646.000000
mean,3.740308e+07,1.482316e+07,1.093613e+07,2.775761e+05,1.377692e+05,68.829516,37.185909,31.204722,3469.355216
std,1.897876e+08,5.910619e+07,4.509525e+07,1.258625e+06,8.145803e+05,60.589002,28.372486,27.154367,4098.988743
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,4.379680e+05,2.979992e+05,1.907230e+05,5.358250e+03,9.780000e+02,11.910000,8.910000,4.880000,685.000000
50%,2.891997e+06,1.836524e+06,1.279190e+06,2.659100e+04,7.945500e+03,54.580000,34.990000,24.870000,2276.000000
75%,1.375549e+07,7.332479e+06,5.802974e+06,1.273322e+05,4.554825e+04,117.490000,63.450000,56.095000,5052.000000
max,2.978646e+09,1.265034e+09,1.224450e+09,2.474100e+07,2.242429e+07,327.790000,122.690000,120.700000,117497.000000

Checkiing If the columns contains null values

In [21]:
df.isnull().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     34800
people_vaccinated                      36755
people_fully_vaccinated                39521
daily_vaccinations_raw                 41795
daily_vaccinations                       363
total_vaccinations_per_hundred         34800
people_vaccinated_per_hundred          36755
people_fully_vaccinated_per_hundred    39521
daily_vaccinations_per_million           363
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

Filling all the float num values with 0

In [24]:
df.fillna(0.0, inplace=True)
df.isnull().sum()

country                                0
iso_code                               0
date                                   0
total_vaccinations                     0
people_vaccinated                      0
people_fully_vaccinated                0
daily_vaccinations_raw                 0
daily_vaccinations                     0
total_vaccinations_per_hundred         0
people_vaccinated_per_hundred          0
people_fully_vaccinated_per_hundred    0
daily_vaccinations_per_million         0
vaccines                               0
source_name                            0
source_website                         0
dtype: int64

Total numbers of country where vaccination is going

In [37]:
df["country"].nunique()

223

Total no of vaccines

In [39]:
df["vaccines"].nunique()

79

In [43]:
nepal = df[df["country"]=="Nepal"]
nepal.count()

country                                356
iso_code                               356
date                                   356
total_vaccinations                     356
people_vaccinated                      356
people_fully_vaccinated                356
daily_vaccinations_raw                 356
daily_vaccinations                     356
total_vaccinations_per_hundred         356
people_vaccinated_per_hundred          356
people_fully_vaccinated_per_hundred    356
daily_vaccinations_per_million         356
vaccines                               356
source_name                            356
source_website                         356
dtype: int64

In [82]:
world_vacc = df["vaccines"].str.split(",",expand=True)
world_vacc

,0,1,2,3,4,5,6,7
0,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
1,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
2,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
3,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
4,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
...,...,...,...,...,...,...,...,...
73004,Oxford/AstraZeneca,Sinopharm/Beijing,Sinovac,Sputnik V,None,None,None,None
73005,Oxford/AstraZeneca,Sinopharm/Beijing,Sinovac,Sputnik V,None,None,None,None
73006,Oxford/AstraZeneca,Sinopharm/Beijing,Sinovac,Sputnik V,None,None,None,None
73007,Oxford/AstraZeneca,Sinopharm/Beijing,Sinovac,Sputnik V,None,None,None,None
73008,Oxford/AstraZeneca,Sinopharm/Beijing,Sinovac,Sputnik V,None,None,None,None

In [83]:
world_vacc.isnull().sum()

0        0
1     9241
2    22866
3    38278
4    59442
5    65899
6    68991
7    72035
dtype: int64

In [84]:
for i ,column in enumerate(world_vacc.columns):
    print(i, column)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7